### ISSUE TITLE
To make website mobile friendly

### ISSUE THREAD

**Issue by Logan1x** [Logan1x/Logan1x.github.io#13]
This website is not mobile friendly Yet, so the task is to make it mobile friendly. If you want to work on this issue then comment here.

**Comment by DigitalDesignerOnline** [comment]
he I would be happy to assist. :)

**Comment by DigitalDesignerOnline** [comment]
I noticed the social icons look like they need to be edited, where were you wanting these located? I am almost done rewriting the page and stylesheet or mobility and getting rid of the primary scroll bar for you as well.

**Comment by DigitalDesignerOnline** [comment]
adding pull request now.

**Comment by Logan1x** [comment]
@DigitalDesignerOnline  the terminal window on the website is looking preety bad so please make it as it was in past .

**Comment by Logan1x** [comment]
I think it's done for now so closing this Issue.
