### ISSUE TITLE
Fix the github, twitter and other png at the right bottom corner of the page.

### ISSUE THREAD

**Issue by Asutosh989** [Logan1x/Logan1x.github.io#15]

**Comment by DigitalDesignerOnline** [comment]
my pull request has addressed this issue and has them as a footer element below the main content box centered with a space between each icon, let me know if I can further enhance this area for you.

**Comment by Asutosh989** [comment]
The issue seems to be solved, if only you can add some animations to that.

**Comment by DigitalDesignerOnline** [comment]
what did you have in mind, colour transition? bounce effect? I got you covered. and am in the middle of preparing a new pull as we speak :) send me your wish list, this genie grants more then 3 ;)

**Comment by Asutosh989** [comment]
To enlarge the icons when hovered over it or bounce effect would be cool. You can also add any animation that you have in mind.

**Comment by francistaberdo** [comment]
i would like to change the icons for a much "cleaner and consistent" look. in relation to that, i'll make it an svg so you can manipulate it using css or javascript


here's the pull request

https://github.com/Logan1x/Logan1x.github.io/pull/19

**Comment by Logan1x** [comment]
@francistaberdo  your PR has some conflicts please resolve it.

**Comment by DigitalDesignerOnline** [comment]
did you still need any further assistance with this project?

**Comment by Logan1x** [comment]
can you share the preview of the website on your desktop mine is still same 
![workspace 1_010](https://user-images.githubusercontent.com/10944610/31369108-c9f9520e-ad9f-11e7-8b95-ca803cecb26d.png)
