### ISSUE TITLE
Make the Site responsive.

### ISSUE THREAD

**Issue by Asutosh989** [Logan1x/Logan1x.github.io#16]
The site needs to be responsive.
@Logan1x would you mind if I assign this to someone to work on?

**Comment by DigitalDesignerOnline** [comment]
I added in a pull request which has made the site responsive. I can further customize if you would like to review and get back to me

**Comment by Logan1x** [comment]
@Asutosh989 No, i won't mind 😊

**Comment by Asutosh989** [comment]
@DigitalDesignerOnline is working on it. So it's fine.

**Comment by vaibhav1729** [comment]
@Logan1x @Asutosh989 added a PR #20, review it. Now, site is mobile responsive.
@DigitalDesignerOnline what you say about it.

**Comment by francistaberdo** [comment]
in addition to making this site responsive, I also changed the icons/logos on the page @Logan1x. please do check my PR so we can talk about it more 😄

**Comment by vaibhav1729** [comment]
Thanks for merging my PR#20 @Logan1x

**Comment by AshBardhan** [comment]
@Logan1x Are you expecting font-size to be responsive as well?

**Comment by Logan1x** [comment]
@Ashbardhan font size and website should be web responsive too.

**Comment by DigitalDesignerOnline** [comment]
check the newest pr I sent you mate responsive with a sticky header and footer.

**Comment by AshBardhan** [comment]
@Logan1x Added PR regarding font responsiveness and other UI fixes. Check #46
