### ISSUE TITLE
Suggestion For making website more better.....

### ISSUE THREAD

**Issue by Logan1x** [Logan1x/Logan1x.github.io#2]

**Comment by Logan1x** [comment]
This is my portfolio website and if you want to help making this by doing open source contribution, you are most welcome.Please Suggest any idea by this website can look more terminal friendly 💻 😈 and then add your name to contributerlist🤗.

**Comment by prakamya-mishra** [comment]
I can add cursor a the end of each para and add a blinking effect to it like this:
<img width="33" alt="screen shot 2017-09-29 at 1 40 18 pm" src="https://user-images.githubusercontent.com/22093105/31006777-d0fc6578-a51b-11e7-9d4d-dc2a3c7c217c.png">

**Comment by prakamya-mishra** [comment]
or even try to embed every content in a div which exactly looks like terminal and a scrolling effect to it

**Comment by Logan1x** [comment]
Looks Great To Me @prakamya-mishra 😊

**Comment by prakamya-mishra** [comment]
When should i give a pull request to get it counted for the 4 pull requests in hactoberfest.(between 1st to 31?)

**Comment by Logan1x** [comment]
Yes! you have to pr between 1-31 oct to count in hactoberfest.

**Comment by meganinj4** [comment]
maybe you should try separate the website in areas, it looks good but its a kind of messy
oh also dont forgot photos

**Comment by prakamya-mishra** [comment]
How does this look like:

<img width="1435" alt="screen shot 2017-09-29 at 3 11 55 pm" src="https://user-images.githubusercontent.com/22093105/31010507-b8d2b332-a528-11e7-80d9-eef9c4886878.png">

**Comment by Logan1x** [comment]
Great 🤘

**Comment by Logan1x** [comment]
Don't you think we should add social media button instead of more info section.. what's your thoughts on this @prakamya-mishra @ahadali

**Comment by Logan1x** [comment]
and top heading should be on the white bar like this
![selection_004](https://user-images.githubusercontent.com/10944610/31013510-0a15b572-a534-11e7-800e-4cc1f7272615.png)

**Comment by Logan1x** [comment]
@ahadali  what's your views on this?

> How does this look like:

**Comment by Logan1x** [comment]
The curves of both rectangle are rounded can you make better 😁 @prakamya-mishra

**Comment by prakamya-mishra** [comment]
ok i will work on it

**Comment by Logan1x** [comment]
**Thanks** 😊 and what about this..

> Don't you think we should add social media button instead of more info section.

**Comment by prakamya-mishra** [comment]
But adding social media icons will not match the theme of terminal, but still I will think of an idea.

**Comment by Logan1x** [comment]
Yes! it's is last thing don't focus it on now...

**Comment by prakamya-mishra** [comment]
I have a Question:
All my pull request should reference to this issue then only will it get counted in hacktoberfest?

**Comment by Logan1x** [comment]
yes they will surely You can check them by signing in hackoctober page from 1 -31 oct 😊.

**Comment by prakamya-mishra** [comment]
I am already signed up and have linked my github repository to them so I
think they will track it automatically.

**Comment by Logan1x** [comment]
yes they will

**Comment by raviigarg** [comment]
![screenshot 4](https://user-images.githubusercontent.com/31215399/31019885-df4c777a-a54e-11e7-88fa-0ad63b968d87.png)


How does this look like?? 
It is responsive for all screen sizes.
I hope you will like it :)

**Comment by Logan1x** [comment]
@garg-ravi24  **Thanks for helping** but @prakamya-mishra is already working on this, You should let me know. Don't worry i've task for you too...
![social](https://user-images.githubusercontent.com/10944610/31020430-9d39d4f2-a550-11e7-9504-dc141524d69f.gif)

i want something like this as social media button So if you can make it then we will add them to final layout😊.

and as a design i like @prakamya-mishra 's design more because it looking more like terminal.

 A Bit of advice - when you are working on issue let other peoples know you are working so that they won't work on same thing.

Again Thanks and let me know if you are working on this or you need some help😊.

[Image Source](https://ask.fedoraproject.org/en/questions/) - Bottom right of the page.

**Comment by raviigarg** [comment]
Yup, i will try.
I have added effects on social media icons but it is little bit different from yours.
And thanks for appreciation :)

**Comment by raviigarg** [comment]
![ezgif-3-5e44a512bf](https://user-images.githubusercontent.com/31215399/31026060-8c863cc4-a562-11e7-8dd8-63462872a219.gif)

I have done like this.
Can I make pull request during the hacktoberfest.

**Comment by prakamya-mishra** [comment]
How does this effect look like?:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22093105/31028654-5f0256c0-a56c-11e7-85ea-ca2db0e1f232.gif)

**Comment by prakamya-mishra** [comment]
Here I have also curves.

**Comment by Logan1x** [comment]
@garg-ravi24 these looks fine to me if you can set them vertically

**Comment by Logan1x** [comment]
@prakamya-mishra this is lovely you can work on this 

And can you send me SS with Khushal Sharma(or intro) written on while line in centre (should be look like application name)

**Comment by Logan1x** [comment]
@garg-ravi24 https://simplesharingbuttons.com/ this might help you in finding websites logo images 🤗

**Comment by prakamya-mishra** [comment]
what about this:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22093105/31034051-0e7bb5de-a580-11e7-97b9-b4df6c71e9a9.gif)

In this to add other things like social media icons you can add it to other components of the screen.

**Comment by raviigarg** [comment]
![screenshot 7](https://user-images.githubusercontent.com/31215399/31041915-ab67c218-a5ba-11e7-9845-112dfaa4b677.png)
How it seems ??
They have the same effect.

**Comment by Logan1x** [comment]
@prakamya-mishra  I asked to other contributer's let's see what they say.  whats your vote on this @garg-ravi24 ?

> what about this:
ezgif com-video-to-gif

In this to add other things like social media icons you can add it to other components of the screen.

**Comment by Logan1x** [comment]
@garg-ravi24  These are fine if you just change the color of github and stackoverflow icon 😊.

**Comment by raviigarg** [comment]
What about this?
![screenshot 9](https://user-images.githubusercontent.com/31215399/31043786-96aba220-a5df-11e7-8025-2bc6ed11fb37.png)
Awesome work @prakamya-mishra

**Comment by Logan1x** [comment]
![selection_001](https://user-images.githubusercontent.com/10944610/31043851-e66bc5be-a5e0-11e7-97e3-ff48ee1644cb.png)
never seen github logo in blue try this type of....

**Comment by Logan1x** [comment]
@prakamya-mishra  MIne and @thomas154 vote is to this one ..waiting for @ahadali's reply then we'll decide😊

![](https://user-images.githubusercontent.com/22093105/31028654-5f0256c0-a56c-11e7-85ea-ca2db0e1f232.gif)

**Comment by raviigarg** [comment]
Now?
![screenshot 10](https://user-images.githubusercontent.com/31215399/31043922-995f6666-a5e2-11e7-8991-f36d0511cb54.png)

**Comment by prakamya-mishra** [comment]
So no laptop right?

**Comment by Logan1x** [comment]
Yes we'll go with first one

**Comment by prakamya-mishra** [comment]
Ok so I will give the PR tomorrow. Then after that we will think of other UI developments.

**Comment by raviigarg** [comment]
Can i  also make the the PR tomorrow.  We can add these social media icons to the outside the middle body. PR request for counted in hactoberfest  should b merged in the original one or not ?

**Comment by Logan1x** [comment]
garg-ravi24 you have to add social media buttons on the new design so when @prakamya-mishra submit's hir pr then you will start working. It's totally depends on you choice when you both submit's you pr😊.

**Comment by prakamya-mishra** [comment]
Will submit it first in the morning tomorrow and then @garg-ravi24  you submit your PR 😄 .

**Comment by raviigarg** [comment]
If i make submit my PR then it will be counted or not? Please merge @prakamya-mishra 's PR so i can start work on the new design . And please do not close this issue untill i will not submit my PR.

**Comment by Logan1x** [comment]
@garg-ravi24  now you can start working

will not close don't worry😊
> And please do not close this issue until I will not submit my PR.

I want social button's on bottom left corner of the screen. paste gif after your work 😊
![selection_002](https://user-images.githubusercontent.com/10944610/31052241-89366e1e-a69c-11e7-9055-452d812d5fdf.png)

**Comment by prakamya-mishra** [comment]
Now what else should i work on @Logan1x ? 🤔

**Comment by Logan1x** [comment]
@prakamya-mishra  open the website in mobile it's not mobile responsive make it reponsive;)

**Comment by Logan1x** [comment]
@garg-ravi24 Please update the contributer's list in readme.md when you are submitting PR

**Comment by raviigarg** [comment]
Sure, I am working.

**Comment by raviigarg** [comment]
What about this?
![ezgif-3-bb11f25cb4](https://user-images.githubusercontent.com/31215399/31053135-ed5eb2e0-a6b3-11e7-8410-d0db55658ace.gif)

**Comment by AshBardhan** [comment]
@Logan1x I see a redundant use of CSS. I can optimize and make your CSS file smaller. Is it OK?

**Comment by AshBardhan** [comment]
@Logan1x Check my PR #46, where I've optimized CSS file.
