### ISSUE TITLE
Add header and footer 

### ISSUE THREAD

**Issue by Logan1x** [Logan1x/Logan1x.github.io#28]

**Comment by ghost** [comment]
I would like to resolve this issue.

**Comment by ghost** [comment]
What exactly do you want the header and footer to have?

**Comment by Logan1x** [comment]
header should have 
![screenshot-2017-10-21 khushal sharma](https://user-images.githubusercontent.com/10944610/31851034-995934ae-b67b-11e7-94fc-130a55f342bc.png)

and footer should be something like this 
![screenshot-2017-10-21 https opensourcehelpcommunity herokuapp com](https://user-images.githubusercontent.com/10944610/31851041-aa6c2f30-b67b-11e7-8b38-f780d5b61d4f.png)

**Comment by ghost** [comment]
@Logan1x OK! I will take it.

**Comment by Logan1x** [comment]
Go on!!

**Comment by ghost** [comment]
@Logan1x  Let me know what your facebook url is.

**Comment by ghost** [comment]
@Logan1x I'm sorry I can't help with the footer I don't know how to stick the footer at the bottom of the page ... it always comes on top of the terminal ...

**Comment by ghost** [comment]
@Logan1x For the social media icons you can use [font-awesome](http://fontawesome.io/)

**Comment by baniksudipta** [comment]
I want to work on the issue. Is it still available?

**Comment by Logan1x** [comment]
@xorz57  don't add facebook icon

**Comment by Logan1x** [comment]
@baniksudipto if @xorz57  having problem in [this ](https://github.com/Logan1x/Logan1x.github.io/issues/28#issuecomment-338385809) you can surely help him.

**Comment by DigitalDesignerOnline** [comment]
you still need help with the header / footer I can assist, you want them sticky or scrollable? I can get it done right away mate. :)

**Comment by DigitalDesignerOnline** [comment]
Let me know if this is what you had in mind and I will get the pr ready for you.
![sticky-header-footer-logan](https://user-images.githubusercontent.com/25376856/31866698-5834acde-b751-11e7-81a5-fec2d929882b.JPG)

**Comment by DigitalDesignerOnline** [comment]
pull request created, let me know if you want any other edits done mate. happy to help again as we did before :)

**Comment by DigitalDesignerOnline** [comment]
@xorz57 check my pr you will get a easy way to make your pages sticky in both header and  footer mate while keeping responsiveness. ;)

**Comment by Logan1x** [comment]
@DigitalDesignerOnline  PR is merged thanks everybody for helping😊.

**Comment by DigitalDesignerOnline** [comment]
Check out index2.html within this zip file. I may not have the most recent repo of yours which could be the issue so I only edited the stylesheet and index. Here is the pull I did downloading your file and editing the stylesheet etc

[Logan1x.github.io-master.zip](https://github.com/Logan1x/Logan1x.github.io/files/1406058/Logan1x.github.io-master.zip)

**Comment by Ram-1998** [comment]
Is this issue open?

**Comment by DigitalDesignerOnline** [comment]
looks like we got the sticky part sorted just tweaking the quora icon in the footer as for some reason the fontawesome quora icon is not wanting to load up. will sort it out :)

**Comment by Logan1x** [comment]
@Ram-1998  no ram pr in review state once it will totally merged ill close this issue.
