### ISSUE TITLE
Change The link in index.html file

### ISSUE THREAD

**Issue by Logan1x** [Logan1x/Logan1x.github.io#4]
Link to the project's in project section are changed due to [redesigning the python script's repo](https://github.com/Logan1x/Python-Scripts/issues/2), So need to update them in index.html file

![selection_004](https://user-images.githubusercontent.com/10944610/31052736-e3d6a768-a6aa-11e7-8591-7e404f14de32.png)

So change them ike this for locate me the new kink should be ' https://github.com/Logan1x/Python-Scripts/blob/master/locate-me.py '

**Comment by Logan1x** [comment]
CC :  @toonarmycaptain this was the issue,if you want to work comment here.

**Comment by QzSG** [comment]
Created pull request #5

**Comment by Logan1x** [comment]
You have to update all three links @QzSG

**Comment by QzSG** [comment]
Fixed! My bad
