### ISSUE TITLE
Exposed API Key

### ISSUE THREAD

**Issue by luking-dev** [Logan1x/Logan1x.github.io#69]
You have your API Key exposed to public in src/app.js file

**Comment by Logan1x** [comment]
Hey, @luckyz I am aware of this. Back then I didn't know about env, going to change it now. Thanks :)

**Comment by Logan1x** [comment]
@luckyz I tried looking for GitHub environment keys but I am not sure we can use this on plane HTML CSS app hosted on github pages. 
Any Idea how can I achieve this?

**Comment by luking-dev** [comment]
You should host your keys in an ```.env```file (no extension) and add it to your ```.gitignore```.
